### ISSUE TITLE
file name starting with an underscore, leads to a compile bug

### ISSUE THREAD

**Issue by hylerrix** [xcatliu/pagic#56]
**Describe the bug**

```
[Pagic] Plugin sidebar start
error: Uncaught TypeError: Cannot read property 'title' of undefined
        title: pagic.pagePropsMap[sidebarConfigItem].title,
                                                     ^
    at https://deno.land/x/pagic@v0.10.3/src/plugins/sidebar.tsx:62:54
    at Array.map (<anonymous>)
    at parseSidebarConfig (https://deno.land/x/pagic@v0.10.3/src/plugins/sidebar.tsx:59:24)
    at Object.fn (https://deno.land/x/pagic@v0.10.3/src/plugins/sidebar.tsx:42:33)
    at Pagic.runPlugins (https://deno.land/x/pagic@v0.10.3/src/Pagic.ts:374:20)
    at async Pagic.rebuild (https://deno.land/x/pagic@v0.10.3/src/Pagic.ts:227:5)
    at async Pagic.build (https://deno.land/x/pagic@v0.10.3/src/Pagic.ts:204:5)
```

**To Reproduce**

* Name a file starting with an underscore, such as `_hello.md`, can not compile success.

**Screenshots**

**Context**
- Pagic version: v0.10.3
- Deno version: v1.4.6
- Browser version (optional): 
- OS version: macOS Big Sur v11(beta, 20A5395g)

**Comment by xcatliu** [comment]
Markdown file starts with `_` will be ignored when compiling.
